# Generated by Django 5.0 on 2023-12-16 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "username",
                    models.CharField(
                        max_length=300,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_username",
                                message="Username must be alphanumeric or contain numbers",
                                regex="^[a-zA-Z0-9.+-]*$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="last login"),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("Cattle&Products", "Cattle&Products"),
                            ("Sheep&Products", "Sheep&Products"),
                            ("Pig&Products", "Pig&Products"),
                            ("Poultry&Products", "Poultry&Products"),
                            ("Others", "Others"),
                            ("Vegetables", "Vegetable"),
                            ("Fruits", "Fruits"),
                        ],
                        max_length=100,
                        verbose_name="Select A Group",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
